# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/cmake-3.16.0-Linux-x86_64/bin/cmake

# The command to remove a file.
RM = /opt/cmake-3.16.0-Linux-x86_64/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Users/world/CLionProjects/grpwk

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Users/world/ClionProjects/grpwk

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/cmake-3.16.0-Linux-x86_64/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/cmake-3.16.0-Linux-x86_64/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/world/ClionProjects/grpwk/CMakeFiles /mnt/c/Users/world/ClionProjects/grpwk/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/world/ClionProjects/grpwk/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named grpwk

# Build rule for target.
grpwk: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 grpwk
.PHONY : grpwk

# fast build rule for target.
grpwk/fast:
	$(MAKE) -f CMakeFiles/grpwk.dir/build.make CMakeFiles/grpwk.dir/build
.PHONY : grpwk/fast

constructions.o: constructions.c.o

.PHONY : constructions.o

# target to build an object file
constructions.c.o:
	$(MAKE) -f CMakeFiles/grpwk.dir/build.make CMakeFiles/grpwk.dir/constructions.c.o
.PHONY : constructions.c.o

constructions.i: constructions.c.i

.PHONY : constructions.i

# target to preprocess a source file
constructions.c.i:
	$(MAKE) -f CMakeFiles/grpwk.dir/build.make CMakeFiles/grpwk.dir/constructions.c.i
.PHONY : constructions.c.i

constructions.s: constructions.c.s

.PHONY : constructions.s

# target to generate assembly for a file
constructions.c.s:
	$(MAKE) -f CMakeFiles/grpwk.dir/build.make CMakeFiles/grpwk.dir/constructions.c.s
.PHONY : constructions.c.s

example/Algorithm_template.o: example/Algorithm_template.c.o

.PHONY : example/Algorithm_template.o

# target to build an object file
example/Algorithm_template.c.o:
	$(MAKE) -f CMakeFiles/grpwk.dir/build.make CMakeFiles/grpwk.dir/example/Algorithm_template.c.o
.PHONY : example/Algorithm_template.c.o

example/Algorithm_template.i: example/Algorithm_template.c.i

.PHONY : example/Algorithm_template.i

# target to preprocess a source file
example/Algorithm_template.c.i:
	$(MAKE) -f CMakeFiles/grpwk.dir/build.make CMakeFiles/grpwk.dir/example/Algorithm_template.c.i
.PHONY : example/Algorithm_template.c.i

example/Algorithm_template.s: example/Algorithm_template.c.s

.PHONY : example/Algorithm_template.s

# target to generate assembly for a file
example/Algorithm_template.c.s:
	$(MAKE) -f CMakeFiles/grpwk.dir/build.make CMakeFiles/grpwk.dir/example/Algorithm_template.c.s
.PHONY : example/Algorithm_template.c.s

example/grpwk.o: example/grpwk.c.o

.PHONY : example/grpwk.o

# target to build an object file
example/grpwk.c.o:
	$(MAKE) -f CMakeFiles/grpwk.dir/build.make CMakeFiles/grpwk.dir/example/grpwk.c.o
.PHONY : example/grpwk.c.o

example/grpwk.i: example/grpwk.c.i

.PHONY : example/grpwk.i

# target to preprocess a source file
example/grpwk.c.i:
	$(MAKE) -f CMakeFiles/grpwk.dir/build.make CMakeFiles/grpwk.dir/example/grpwk.c.i
.PHONY : example/grpwk.c.i

example/grpwk.s: example/grpwk.c.s

.PHONY : example/grpwk.s

# target to generate assembly for a file
example/grpwk.c.s:
	$(MAKE) -f CMakeFiles/grpwk.dir/build.make CMakeFiles/grpwk.dir/example/grpwk.c.s
.PHONY : example/grpwk.c.s

input_win.o: input_win.c.o

.PHONY : input_win.o

# target to build an object file
input_win.c.o:
	$(MAKE) -f CMakeFiles/grpwk.dir/build.make CMakeFiles/grpwk.dir/input_win.c.o
.PHONY : input_win.c.o

input_win.i: input_win.c.i

.PHONY : input_win.i

# target to preprocess a source file
input_win.c.i:
	$(MAKE) -f CMakeFiles/grpwk.dir/build.make CMakeFiles/grpwk.dir/input_win.c.i
.PHONY : input_win.c.i

input_win.s: input_win.c.s

.PHONY : input_win.s

# target to generate assembly for a file
input_win.c.s:
	$(MAKE) -f CMakeFiles/grpwk.dir/build.make CMakeFiles/grpwk.dir/input_win.c.s
.PHONY : input_win.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... grpwk"
	@echo "... constructions.o"
	@echo "... constructions.i"
	@echo "... constructions.s"
	@echo "... example/Algorithm_template.o"
	@echo "... example/Algorithm_template.i"
	@echo "... example/Algorithm_template.s"
	@echo "... example/grpwk.o"
	@echo "... example/grpwk.i"
	@echo "... example/grpwk.s"
	@echo "... input_win.o"
	@echo "... input_win.i"
	@echo "... input_win.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

